config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :game_consoles
  root 'game_consoles#index'
end

app/models/game_console.rb
class GameConsole < ActiveRecord::Base
  validates :name, presence: true
  validates :manufacturer, presence: true
  validates :year, presence: true
  validates :year, numericality: { only_integer: true }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_consoles_controller.rb
class GameConsolesController < ApplicationController
  before_action :set_game_console, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @game_consoles = GameConsole.all
    respond_with(@game_consoles)
  end

  def show
    respond_with(@game_console)
  end

  def new
    @game_console = GameConsole.new
    respond_with(@game_console)
  end

  def edit
  end

  def create
    @game_console = GameConsole.new(game_console_params)
    @game_console.save
    respond_with(@game_console)
  end

  def update
    @game_console.update(game_console_params)
    respond_with(@game_console)
  end

  def destroy
    @game_console.destroy
    respond_with(@game_console)
  end

  private
    def set_game_console
      @game_console = GameConsole.find(params[:id])
    end

    def game_console_params
      params.require(:game_console).permit(:name, :manufacturer, :year)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/game_consoles_helper.rb
module GameConsolesHelper
end

app/views/game_consoles/_form.html.erb
<%= form_for(@game_console) do |f| %>
  <% if @game_console.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_console.errors.count, "error") %> prohibited this game_console from being saved:</h2>

      <ul>
      <% @game_console.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br>
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_consoles/edit.html.erb
<h1>Editing Game Console</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_console %> |
<%= link_to 'Back', game_consoles_path %>

app/views/game_consoles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Game Consoles</h1>

<table class="tablesorter">
  <thead>
    <tr>
      <th>Name</th>
      <th>Manufacturer</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_consoles.each do |game_console| %>
      <tr>
        <td><%= game_console.name %></td>
        <td><%= game_console.manufacturer %></td>
        <td><%= game_console.year %></td>
        <td><%= link_to 'Show', game_console %></td>
        <td><%= link_to 'Edit', edit_game_console_path(game_console) %></td>
        <td><%= link_to 'Destroy', game_console, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game console', new_game_console_path %>

app/views/game_consoles/new.html.erb
<h1>New Game Console</h1>

<%= render 'form' %>

<%= link_to 'Back', game_consoles_path %>

app/views/game_consoles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game_console.name %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @game_console.manufacturer %>
</p>

<p>
  <strong>Year:</strong>
  <%= @game_console.year %>
</p>

<%= link_to 'Edit', edit_game_console_path(@game_console) %> |
<%= link_to 'Back', game_consoles_path %>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="flash flash-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="flash flash-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>SortingTables</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">SortingTables</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <% if current_user %>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <% end %>
      </ul>
    </section>
  </nav>

  <%= render "layouts/flashes" %>

  <div class="row">
    <%= yield %>
  </div>

  <%= javascript_include_tag 'application' %>
</body>
</html>